version: '3.6'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #- ./gitlab-runner/config:/etc/gitlab-runner
